// <auto-generated />
namespace Haiku.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Configuring_Table_Relationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuring_Table_Relationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201512061631433_Configuring_Table_Relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
