// <auto-generated />
namespace Haiku.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_User_AccessToken_Length_To_128 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_User_AccessToken_Length_To_128));
        
        string IMigrationMetadata.Id
        {
            get { return "201512120025407_Change_User_AccessToken_Length_To_128"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
