// <auto-generated />
namespace Haiku.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IX_User_AccessToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_User_AccessToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201512071957527_IX_User_AccessToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
